version: 0
tasks:
  - provisionerId: '{{taskcluster.docker.provisionerId}}'
scopes:
  - generic-worker:os-group:relops-3/win2019/Administrators
  - generic-worker:run-as-administrator:relops-3/win2019
  - queue:route:index.project.releng.relops-image-builder.v1.revision.{{event.head.sha}}
  - queue:create-task:relops-3/win2019
    routes:
      - index.project.releng.relops-image-builder.v1.revision.{{event.head.sha}}
    workerType: '{{taskcluster.docker.workerType}}'
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
      data:
        base:
          sha: '{{event.base.sha}}'
          user:
            login: '{{event.base.user.login}}'
        head:
          sha: '{{event.head.sha}}'
          user:
            email: '{{event.head.user.email}}'
    payload:
      maxRunTime: 600
      image: 'grenade/opencloudconfig'
      features:
        taskclusterProxy: true
      command:
        - '/bin/bash'
        - '--login'
        - '-c'
        - 'git clone --quiet {{event.head.repo.url}} && git --git-dir=./relops-image-builder/.git --work-tree=./relops-image-builder fetch && git --git-dir=./relops-image-builder/.git --work-tree=./relops-image-builder checkout {{event.head.repo.branch}} && export git_changed_files=$(git --git-dir=./relops-image-builder/.git --work-tree=./relops-image-builder diff --name-only HEAD~1) && printenv && echo $(curl -sI http://taskcluster | grep X-Taskcluster-Proxy-Version) && pip install taskcluster && python ./relops-image-builder/ci/decision-task.py'
    metadata:
      name: 'decision-task'
      description: 'Create CI tasks for the current commit'
      owner: '{{event.head.user.email}}'
      source: '{{event.head.repo.url}}'
allowPullRequests: collaborators